[versions]
lombok = "1.18.42"
minestom = "2026.01.08-1.21.11"
slf4j = "2.0.17"
logback = "1.5.32"
luckperms = "5.5-SNAPSHOT"
configurate = "4.2.0"
hikari = "7.0.2"
h2database = "2.4.240"
polar = "1.15.0"
fastutil = "8.5.18"
axiom = "0.0.4"
spark = "1.10-SNAPSHOT"
bytesocks-java-client = "1.0-SNAPSHOT"


[libraries]
# Common
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
minestom = { module = "net.minestom:minestom", version.ref = "minestom" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
luckperms = { module = "dev.lu15:luckperms-minestom", version.ref = "luckperms" }
sponge-configurate-core = { module = "org.spongepowered:configurate-core", version.ref = "configurate" }
sponge-configurate-hocon = { module = "org.spongepowered:configurate-hocon", version.ref = "configurate" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
h2database = { module = "com.h2database:h2", version.ref = "h2database" }
minestom-polar = { module = "dev.hollowcube:polar", version.ref = "polar" }
fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }
minestom-axiom = { module = "fr.ghostrider584:axiom-minestom", version.ref = "axiom" }
minestom-spark = { module = "dev.lu15:spark-minestom", version.ref = "spark" }
bytesocks-java-client = { module = "me.lucko:bytesocks-java-client", version.ref = "bytesocks-java-client" }